[workspace]
resolver = "2"
members = [
    "crates/graphite",
    "crates/graphite-codegen",
    "crates/graphite-macros",
    "xtask",
]

[workspace.dependencies]
petgraph = "0.6"
syn = { version = "2", features = ["full", "visit"] }
quote = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
prettyplease = "0.2"
